services:
  web:
    image: web:latest
    container_name: web
    environment:
      DB_USER: app
      DB_PASSWORD: password
      DB_HOST: mysql
      DB_NAME: api_database
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
    networks:
      - api-networks
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8080/health"]
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 3s
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: app
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: api_database
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql"]
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 5s
    restart: always
    volumes:
      - ./external-apps/db/:/docker-entrypoint-initdb.d
    networks:
      - api-networks
  mysql-cli:
    image: mysql:8.0
    command: mysql -hmysql -u app -ppassword api_database
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - api-networks

networks:
  api-networks:
    driver: bridge
